---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  warning = F
)
```

# ggcalendar

<!-- badges: start -->
<!-- badges: end -->

Create grammar of graphics calendars.  


```{r}
library(ggcalendar)
library(ggplot2)
library(lubridate)
library(tidyverse)
```


``` r
# install.packages("devtools")
devtools::install_github("EvaMaeRey/ggcalendar")
```
## Example

```{r}
compute_group_calendar_script <- readLines("./R/compute_group_calendar.R")
```

```{r count, code = compute_group_calendar_script}

```

```{r}
# compute function
return_dates_year(1999) %>%
head() %>%
compute_group_calendar()
```


```{r example}

## basic example code

return_dates_year(2022) %>% 
ggplot(data = .) + 
  aes(date = date) + 
  facet_wrap(~month(date, label = T)) + 
  geom_text_calendar(aes(label = day(date))) + 
  geom_point_calendar(data = data.frame(date = c("2022-03-19", "2022-04-09")),
                      color = 'red',
                      size = 8, alpha = .5) + 
  geom_point_calendar(data = data.frame(date = c("2022-05-07")),
                      color = 'goldenrod3',
                      size = 8, alpha = .6) + 
  labs(title = "nu2ggplot2X10sion") + 
  scale_y_reverse()

```

